language: python
python:
  - "2.7"
services: mongodb
env:
  - TOX_ENV=py27-mongo
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
before_install:
  # Hack! See https://github.com/travis-ci/travis-ci/issues/7940
  - sudo rm -f /etc/boto.cfg
