language: python
python:
  - "2.7"
  - "3.3"
  - "pypy"
services: mongodb
env:
  - TOX_ENV=py27-mongo
  - TOX_ENV=py33-mongo
  - TOX_ENV=pypy-mongo
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
before_install:
  # Hack! See https://github.com/travis-ci/travis-ci/issues/7940
  - sudo rm -f /etc/boto.cfg
