sudo: false
language: python
python:
  - "2.7"
  - "3.6"
services: mongodb
install: pip install tox-travis
script: tox
before_install:
  # Hack! See https://github.com/travis-ci/travis-ci/issues/7940
  - sudo rm -f /etc/boto.cfg